mesh:
  obj_0:
    file_path: scene/arch/0.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_1:
    file_path: scene/arch/1.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_2:
    file_path: scene/arch/2.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_3:
    file_path: scene/arch/3.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_4:
    file_path: scene/arch/4.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_5:
    file_path: scene/arch/5.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_6:
    file_path: scene/arch/6.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_7:
    file_path: scene/arch/7.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_8:
    file_path: scene/arch/8.obj
    pose: [0, 0, 0, 1, 0, 0, 0]

cuboid:
  obj_9:
    dims: [5.0, 5.0, 0.2] # x, y, z
    pose: [1.0, 0.0, -0.1, 1, 0, 0, 0.0] # x, y, z, qx, qy, qz, qw
    color: [1.0, 1.0, 1.0]
