mesh:
  obj_0:
    file_path: scene/mini/0.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_1:
    file_path: scene/mini/1.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_10:
    file_path: scene/mini/10.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_100:
    file_path: scene/mini/100.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_101:
    file_path: scene/mini/101.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_102:
    file_path: scene/mini/102.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_11:
    file_path: scene/mini/11.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_12:
    file_path: scene/mini/12.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_13:
    file_path: scene/mini/13.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_14:
    file_path: scene/mini/14.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_15:
    file_path: scene/mini/15.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_16:
    file_path: scene/mini/16.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_17:
    file_path: scene/mini/17.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_18:
    file_path: scene/mini/18.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_19:
    file_path: scene/mini/19.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_2:
    file_path: scene/mini/2.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_20:
    file_path: scene/mini/20.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_21:
    file_path: scene/mini/21.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_22:
    file_path: scene/mini/22.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_23:
    file_path: scene/mini/23.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_24:
    file_path: scene/mini/24.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_25:
    file_path: scene/mini/25.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_26:
    file_path: scene/mini/26.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_27:
    file_path: scene/mini/27.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_28:
    file_path: scene/mini/28.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_29:
    file_path: scene/mini/29.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_3:
    file_path: scene/mini/3.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_30:
    file_path: scene/mini/30.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_31:
    file_path: scene/mini/31.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_32:
    file_path: scene/mini/32.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_33:
    file_path: scene/mini/33.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_34:
    file_path: scene/mini/34.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_35:
    file_path: scene/mini/35.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_36:
    file_path: scene/mini/36.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_37:
    file_path: scene/mini/37.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_38:
    file_path: scene/mini/38.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_39:
    file_path: scene/mini/39.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_4:
    file_path: scene/mini/4.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_40:
    file_path: scene/mini/40.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_41:
    file_path: scene/mini/41.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_42:
    file_path: scene/mini/42.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_43:
    file_path: scene/mini/43.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_44:
    file_path: scene/mini/44.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_45:
    file_path: scene/mini/45.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_46:
    file_path: scene/mini/46.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_47:
    file_path: scene/mini/47.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_48:
    file_path: scene/mini/48.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_49:
    file_path: scene/mini/49.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_5:
    file_path: scene/mini/5.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_50:
    file_path: scene/mini/50.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_51:
    file_path: scene/mini/51.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_52:
    file_path: scene/mini/52.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_53:
    file_path: scene/mini/53.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_54:
    file_path: scene/mini/54.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_55:
    file_path: scene/mini/55.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_56:
    file_path: scene/mini/56.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_57:
    file_path: scene/mini/57.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_58:
    file_path: scene/mini/58.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_59:
    file_path: scene/mini/59.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_6:
    file_path: scene/mini/6.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_60:
    file_path: scene/mini/60.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_61:
    file_path: scene/mini/61.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_62:
    file_path: scene/mini/62.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_63:
    file_path: scene/mini/63.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_64:
    file_path: scene/mini/64.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_65:
    file_path: scene/mini/65.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_66:
    file_path: scene/mini/66.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_67:
    file_path: scene/mini/67.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_68:
    file_path: scene/mini/68.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_69:
    file_path: scene/mini/69.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_7:
    file_path: scene/mini/7.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_70:
    file_path: scene/mini/70.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_71:
    file_path: scene/mini/71.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_72:
    file_path: scene/mini/72.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_73:
    file_path: scene/mini/73.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_74:
    file_path: scene/mini/74.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_75:
    file_path: scene/mini/75.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_76:
    file_path: scene/mini/76.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_77:
    file_path: scene/mini/77.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_78:
    file_path: scene/mini/78.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_79:
    file_path: scene/mini/79.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_8:
    file_path: scene/mini/8.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_80:
    file_path: scene/mini/80.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_81:
    file_path: scene/mini/81.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_82:
    file_path: scene/mini/82.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_83:
    file_path: scene/mini/83.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_84:
    file_path: scene/mini/84.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_85:
    file_path: scene/mini/85.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_86:
    file_path: scene/mini/86.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_87:
    file_path: scene/mini/87.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_88:
    file_path: scene/mini/88.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_89:
    file_path: scene/mini/89.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_9:
    file_path: scene/mini/9.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_90:
    file_path: scene/mini/90.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_91:
    file_path: scene/mini/91.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_92:
    file_path: scene/mini/92.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_93:
    file_path: scene/mini/93.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_94:
    file_path: scene/mini/94.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_95:
    file_path: scene/mini/95.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_96:
    file_path: scene/mini/96.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_97:
    file_path: scene/mini/97.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_98:
    file_path: scene/mini/98.obj
    pose: [0, 0, 0, 1, 0, 0, 0]
  obj_99:
    file_path: scene/mini/99.obj
    pose: [0, 0, 0, 1, 0, 0, 0]

cuboid:
  obj_103:
    dims: [5.0, 5.0, 0.2] # x, y, z
    pose: [1.0, 0.0, -0.1, 1, 0, 0, 0.0] # x, y, z, qx, qy, qz, qw
    color: [1.0, 1.0, 1.0]
    texture: "invisible"