planning:
  n_robot: 1
  base_link_names: [ "base_link" ]
  tool_link_names: [ "tool0"]
  tools:
    n_spheres: [50]
    shapes: [ "L" ]
    radii: [ 0.02 ]
    densities: [ 0.5 ]
    rot_samples: [ 8 ]
    planarity: [ 13 ]
  jnds: [ [ 0, 1, 2, 3, 4, 5 ] ]
  part_preloading_frames: [ [ [ 1, 0, 0, 0 ],
                           [ 0, -1, 0, -1 ],
                           [ 0, 0, -1, 0.5 ],
                           [ 0, 0, 0, 1 ] ]
  ]
  part_loading_frames: [ [ [ 1, 0, 0, 0 ],
                           [ 0, 1, 0, -1 ],
                           [ 0, 0, 1, 0.1 ],
                           [ 0, 0, 0, 1 ] ]
  ]
  tool_frames: [[[0, 0, 1, 0.136],
                 [0, 1, 0, 0],
                 [-1, 0, 0, 0.142],
                 [0, 0, 0, 1]]
  ]
  ik_solver: "abb2600"
  joint_names: [ ['joint_1', 'joint_2', 'joint_3',  'joint_4',  'joint_5', 'joint_6']]

robot_cfg:
  kinematics:
    usd_path: "robot/abb_irb2600_single.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: { }
    usd_flip_joint_limits: [ ]

    urdf_path: "robot/abb_irb2600_single.urdf"
    asset_root_path: "robot/"

    base_link: "world"
    ee_link: "tool0"
    link_names: [ 'base_link', "link_1", "link_2",
                  "link_3", "link_4", "link_5", "link_6", 'tool0', 'flange']
    lock_joints: null
    extra_links: null

    collision_link_names: ['base_link', 'link_1', 'link_2', 'link_3', 'link_4',  "tool0"]
    collision_spheres:
      base_link:
        - "center": [ -0.004, -0.017, 0.171 ]
          "radius": 0.143
        - "center": [ -0.268, -0.066, 0.167 ]
          "radius": 0.134
        - "center": [ -0.247, 0.094, 0.171 ]
          "radius": 0.126
        - "center": [ -0.004, 0.15, 0.129 ]
          "radius": 0.108
        - "center": [ 0.038, -0.149, 0.129 ]
          "radius": 0.108
      link_1:
        - "center": [ -0.061, 0.0, -0.0 ]
          "radius": 0.2
        - "center": [ 0.121, 0.197, 0.0 ]
          "radius": 0.12
        - "center": [ 0.135, 0.0, -0.0 ]
          "radius": 0.2
      link_2:
        - "center": [ 0.001, -0.155, 0.001 ]
          "radius": 0.14
        - "center": [ 0.004, -0.166, 0.872 ]
          "radius": 0.11
        - "center": [ 0.002, -0.157, 0.158 ]
          "radius": 0.136
        - "center": [ 0.002, -0.159, 0.309 ]
          "radius": 0.133
        - "center": [ 0.003, -0.161, 0.457 ]
          "radius": 0.13
        - "center": [ 0.003, -0.163, 0.6 ]
          "radius": 0.116
        - "center": [ 0.003, -0.164, 0.738 ]
          "radius": 0.113
      link_3:
        - "center": [ 0.024, 0.026, 0.121 ]
          "radius": 0.21
        - "center": [ 0.024, 0.026, 0.0511 ]
          "radius": 0.21
      link_4:
        - "center": [ 0.252, 0.0, -0.0 ]
          "radius": 0.12
        - "center": [ 0.778, 0.0, -0.0 ]
          "radius": 0.12
        - "center": [ 0.357, 0.0, -0.0 ]
          "radius": 0.11
        - "center": [ 0.463, 0.0, -0.0 ]
          "radius": 0.11
        - "center": [ 0.568, 0.0, -0.0 ]
          "radius": 0.11
        - "center": [ 0.673, 0.0, -0.0 ]
          "radius": 0.11
      tool0: null
    collision_sphere_buffer: 0.0
    extra_collision_spheres: { }
    self_collision_ignore: { "base_link": [ "link_1", "link_2" ],
                             "link_1": [ "link_2" ],
                             "link_2": [ "link_3", "link_4" ],
                             "link_3": [ "link_4" ],
                             "link_4": [ "tool0" ],
    }
    self_collision_buffer: { 'base_link': 0.0,
                             'link_1': 0.0,
                             'link_2': 0,
                             'link_3': 0,
                             'link_4': 0
    }

    use_global_cumul: True
    mesh_link_names: [ 'base_link', "link_1", "link_2",
                       "link_3", "link_4", "link_5", "link_6", "flange"] # List[str]

    cspace:
      joint_names: [ 'joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6' ]
      retract_config: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
      null_space_weight: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
      cspace_distance_weight: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
      max_jerk: 500.0
      max_acceleration: 150.0


